defaults: &defaults
  constants_translate_root: constants
  uniform_number:
    min: 1
    max: 99

  member_type:
    none: 0
    player: 1
    manager: 2

  game_time_range:
    min: 0
    max: 999

  home_or_away:
    none: 0
    home: 1
    away: 2

  position:
    - GK
    - DF
    - MF
    - FW

  foul_type:
    none: 0
    caution: &foul_caution
             !int 1
    dismissal: &foul_dismissal
             !int 2

# foul_typeはfoul_typesから参照したいけど
# 参照するとsettingslogicで型が文字列となってしまうので直接指定
#
# またfouls配下の順番を変更すると大変なことになるので
# 項目を追加する場合は下に追加すること
  fouls:
    - symbol: 'C1'
      foul_type: 1
    - symbol: 'C2'
      foul_type: 1
    - symbol: 'C3'
      foul_type: 1
    - symbol: 'C4'
      foul_type: 1
    - symbol: 'C5'
      foul_type: 1
    - symbol: 'C6'
      foul_type: 1
    - symbol: 'C7'
      foul_type: 1
    - symbol: 'C8'
      foul_type: 1
    - symbol: 'S1'
      foul_type: 2
    - symbol: 'S2'
      foul_type: 2
    - symbol: 'S3'
      foul_type: 2
    - symbol: 'S4'
      foul_type: 2
    - symbol: 'S5'
      foul_type: 2
    - symbol: 'S6'
      foul_type: 2
    - symbol: 'CS'
      foul_type: 2

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

