defaults: &defaults
  uniform_number:
    min: 1
    max: 99
  member_types:
    none: 0
    player: 1
    manager: 2
  game_time_range:
    min: 0
    max: 999
  home_or_away:
    none: 0
    home: 1
    away: 2

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

